#include "Core/Precompiled.h"
#include "Graphics/Utility/DXGIFormatUtils.h"
#include "DevTools/EnumText/EnumTextDXGI.h"
#include "DevTools/EnumText/EnumTextGraphics.h"
#include "DevTools/DevelopGui/Panels/IBLViewerPanel.h"
#include "DevTools/DevelopGui/DevelopGuiBackend.h"
#include "DevTools/DevelopGui/DevelopGuiContext.h"
#include "Graphics/Renderer.h"

namespace gglab
{
	namespace
	{
		struct IBLViewerPanelState
		{
			float m_BrdfLutPreviewSize = 256.0f;
			float m_EnvironmentPreviewWidth = 512.0f;
			float m_PrefilteredSpecularPreviewWidth = 512.0f;
			bool m_ShowMetadata = true;
			bool m_FlipPreviewY = false;
		};

		static ImTextureID ToImGuiTextureID(
			Renderer* renderer,
			RHIDescriptorHandle descriptor) noexcept
		{
			auto* backend = renderer ? renderer->GetDevelopGuiBackend() : nullptr;
			return backend ? backend->ResolveTextureId(descriptor) : ImTextureID{};
		}

		static bool DrawPreviewLayoutCombo(const char* label, RenderResourceRegistry::IBLPreviewLayout& layout) noexcept
		{
			using PreviewLayout = RenderResourceRegistry::IBLPreviewLayout;
			bool changed = false;

			if (ImGui::BeginCombo(label, devtools::EnumText(layout).data()))
			{
				const PreviewLayout layouts[] = {
					PreviewLayout::Grid2x3,
					PreviewLayout::Cross,
				};

				for (const auto candidate : layouts)
				{
					const bool selected = (layout == candidate);
					if (ImGui::Selectable(devtools::EnumText(candidate).data(), selected))
					{
						layout = candidate;
						changed = true;
					}
					if (selected)
					{
						ImGui::SetItemDefaultFocus();
					}
				}

				ImGui::EndCombo();
			}

			return changed;
		}
	}

	void IBLViewerPanel::Draw(DevelopGuiContext& context) noexcept
	{
		auto& state = context.PanelState<IBLViewerPanelState>();

		ImGui::TextUnformatted("IBL Viewer");
		ImGui::Separator();

		auto* renderer = context.m_Renderer;
		if (!renderer)
		{
			ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f), "Renderer is null.");
			return;
		}

		auto* renderResRegistry = renderer->GetRenderResourceRegistry();
		if (!renderResRegistry)
		{
			ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f), "RenderResourceRegistry is null.");
			return;
		}

		using TextureIndex = RenderResourceRegistry::TextureIndex;
		constexpr TextureIndex EnvironmentIndex = TextureIndex::IBL_EnvironmentCubemap;
		constexpr TextureIndex EnvironmentPreviewIndex = TextureIndex::Preview_IBL_EnvironmentCubemap;
		constexpr TextureIndex PrefilteredSpecularIndex = TextureIndex::IBL_PrefilteredSpecularCubemap;
		constexpr TextureIndex PrefilteredSpecularPreviewIndex = TextureIndex::Preview_IBL_PrefilteredSpecularCubemap;
		constexpr TextureIndex BrdfLutIndex = TextureIndex::IBL_BrdfLut;

		// Make sure the persistent BRDF LUT resource exists.
		// This only creates the texture and descriptor if missing.
		// Actual content is generated by RenderPassIBLBrdfLUT.
		renderResRegistry->EnsureIblResources();

		const auto* brdfLutDesc = renderResRegistry->GetTextureDesc(BrdfLutIndex);
		if (!brdfLutDesc)
		{
			ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f), "BRDF LUT texture is not allocated.");
			return;
		}

		if (ImGui::CollapsingHeader("IBL BRDF LUT"))
		{
			if (ImGui::Button("Rebuild BRDF LUT"))
			{
				renderResRegistry->MarkDirty(BrdfLutIndex);
			}

			ImGui::SameLine();

			const bool isDirty = renderResRegistry->IsDirty(BrdfLutIndex);
			if (isDirty)
			{
				ImGui::TextColored(ImVec4(1.0f, 0.75f, 0.2f, 1.0f), "Dirty");
			}
			else
			{
				ImGui::TextColored(ImVec4(0.35f, 1.0f, 0.35f, 1.0f), "Ready");
			}

			ImGui::Checkbox("Show Metadata", &state.m_ShowMetadata);

			if (state.m_ShowMetadata)
			{
				const uint32_t srvIndex = renderResRegistry->GetShaderVisibleSrvIndex(BrdfLutIndex);

				ImGui::Text("Size: %llu x %u",
					static_cast<unsigned long long>(brdfLutDesc->m_Extent.m_Width),
					brdfLutDesc->m_Extent.m_Height);

				ImGui::Text("MipLevels: %u", brdfLutDesc->m_MipLevels);
				ImGui::Text("Format: %s", devtools::EnumText(ToDXGIFormat(brdfLutDesc->m_Format)).data());
				ImGui::Text("Shader Visible SRV Index: %u", srvIndex);
			}

			ImGui::Separator();

			ImGui::SliderFloat(
				"Preview Size",
				&state.m_BrdfLutPreviewSize,
				64.0f,
				512.0f,
				"%.0f");

			ImGui::Checkbox("Flip Preview Y", &state.m_FlipPreviewY);

			const ImTextureID textureId = ToImGuiTextureID(
				renderer,
				renderResRegistry->GetSrvDescriptor(BrdfLutIndex));

			if (!textureId)
			{
				ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f), "BRDF LUT SRV GPU handle is invalid.");
				return;
			}

			const float previewSize = std::clamp(state.m_BrdfLutPreviewSize, 16.0f, 2048.0f);
			const ImVec2 imageSize(previewSize, previewSize);

			const ImVec2 uv0 = state.m_FlipPreviewY
				? ImVec2(0.0f, 1.0f)
				: ImVec2(0.0f, 0.0f);

			const ImVec2 uv1 = state.m_FlipPreviewY
				? ImVec2(1.0f, 0.0f)
				: ImVec2(1.0f, 1.0f);

			ImGui::TextUnformatted("Preview");
			ImGui::Image(textureId, imageSize, uv0, uv1);

			ImVec2 imageMin = ImGui::GetItemRectMin();
			ImVec2 imageMax = ImGui::GetItemRectMax();

			if (ImGui::IsItemHovered())
			{
				ImVec2 mouse = ImGui::GetMousePos();

				float u = (mouse.x - imageMin.x) / (imageMax.x - imageMin.x);
				float v = (mouse.y - imageMin.y) / (imageMax.y - imageMin.y);

				u = std::clamp(u, 0.0f, 1.0f);
				v = std::clamp(v, 0.0f, 1.0f);

				if (state.m_FlipPreviewY)
				{
					v = 1.0f - v;
				}

				ImGui::BeginTooltip();
				ImGui::Text("NoV: %.3f", u);
				ImGui::Text("Perceptual Roughness: %.3f", v);
				ImGui::EndTooltip();
			}

			ImGui::TextDisabled("Expected axis: X = NoV, Y = perceptual roughness.");
		}

		ImGui::Spacing();

		const auto* environmentDesc = renderResRegistry->GetTextureDesc(EnvironmentIndex);
		const auto* environmentPreviewDesc = renderResRegistry->GetTextureDesc(EnvironmentPreviewIndex);

		if (ImGui::CollapsingHeader("IBL Environment"))
		{
			if (ImGui::Button("Rebuild Environment"))
			{
				renderResRegistry->MarkDirty(EnvironmentIndex);
			}

			ImGui::SameLine();

			if (renderResRegistry->IsDirty(EnvironmentIndex))
			{
				ImGui::TextColored(ImVec4(1.0f, 0.75f, 0.2f, 1.0f), "Dirty");
			}
			else
			{
				ImGui::TextColored(ImVec4(0.35f, 1.0f, 0.35f, 1.0f), "Ready");
			}

			if (!environmentDesc || !environmentPreviewDesc)
			{
				ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f), "Environment preview texture is not allocated.");
				return;
			}

			using PreviewLayout = RenderResourceRegistry::IBLPreviewLayout;
			PreviewLayout previewLayout = renderResRegistry->GetIBLEnvironmentPreviewLayout();
			if (DrawPreviewLayoutCombo("Display Mode##EnvironmentPreviewLayout", previewLayout))
			{
				renderResRegistry->SetIBLEnvironmentPreviewLayout(previewLayout);
			}

			if (state.m_ShowMetadata)
			{
				const uint32_t environmentSrvIndex = renderResRegistry->GetShaderVisibleSrvIndex(EnvironmentIndex);
				const uint32_t previewSrvIndex = renderResRegistry->GetShaderVisibleSrvIndex(EnvironmentPreviewIndex);

				ImGui::Text("Environment Size: %llu x %u x %u",
					static_cast<unsigned long long>(environmentDesc->m_Extent.m_Width),
					environmentDesc->m_Extent.m_Height,
					environmentDesc->m_ArraySize);
				ImGui::Text("Environment Format: %s", devtools::EnumText(ToDXGIFormat(environmentDesc->m_Format)).data());
				ImGui::Text("Environment Shader Visible SRV Index: %u", environmentSrvIndex);

				ImGui::Text("Preview Canvas Size: %llu x %u",
					static_cast<unsigned long long>(environmentPreviewDesc->m_Extent.m_Width),
					environmentPreviewDesc->m_Extent.m_Height);
				ImGui::Text("Preview Format: %s", devtools::EnumText(ToDXGIFormat(environmentPreviewDesc->m_Format)).data());
				ImGui::Text("Preview Shader Visible SRV Index: %u", previewSrvIndex);
			}

			ImGui::SliderFloat(
				"Environment Preview Width",
				&state.m_EnvironmentPreviewWidth,
				192.0f,
				768.0f,
				"%.0f");

			const ImTextureID environmentPreviewTextureId =
				ToImGuiTextureID(
					renderer,
					renderResRegistry->GetSrvDescriptor(EnvironmentPreviewIndex));

			if (!environmentPreviewTextureId)
			{
				ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f), "Environment preview SRV GPU handle is invalid.");
				return;
			}

			const float environmentPreviewWidth = std::clamp(state.m_EnvironmentPreviewWidth, 16.0f, 2048.0f);

			ImVec2 uv0(0.0f, 0.0f);
			ImVec2 uv1(1.0f, 1.0f);
			float aspect = 3.0f / 4.0f;
			const char* layoutHint = "Cross Layout: +Y / -X +Z +X -Z / -Y";

			if (previewLayout == PreviewLayout::Grid2x3)
			{
				uv1 = ImVec2(3.0f / 4.0f, 2.0f / 3.0f);
				aspect = 2.0f / 3.0f;
				layoutHint = "2x3 Layout: +X -X +Y / -Y +Z -Z";
			}

			const ImVec2 environmentImageSize(environmentPreviewWidth, environmentPreviewWidth * aspect);

			ImGui::TextUnformatted(layoutHint);
			ImGui::Image(environmentPreviewTextureId, environmentImageSize, uv0, uv1);
		}

		ImGui::Spacing();

		const auto* prefilteredSpecularDesc = renderResRegistry->GetTextureDesc(PrefilteredSpecularIndex);
		const auto* prefilteredSpecularPreviewDesc = renderResRegistry->GetTextureDesc(PrefilteredSpecularPreviewIndex);

		if (ImGui::CollapsingHeader("IBL Prefiltered Specular"))
		{
			if (ImGui::Button("Rebuild Prefiltered Specular"))
			{
				renderResRegistry->MarkDirty(PrefilteredSpecularIndex);
			}

			ImGui::SameLine();

			if (renderResRegistry->IsDirty(PrefilteredSpecularIndex))
			{
				ImGui::TextColored(ImVec4(1.0f, 0.75f, 0.2f, 1.0f), "Dirty");
			}
			else
			{
				ImGui::TextColored(ImVec4(0.35f, 1.0f, 0.35f, 1.0f), "Ready");
			}

			if (!prefilteredSpecularDesc || !prefilteredSpecularPreviewDesc)
			{
				ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f), "Prefiltered specular preview texture is not allocated.");
				return;
			}

			const uint32_t mipLevels = prefilteredSpecularDesc->m_MipLevels;
			const uint32_t maxMip = mipLevels > 0 ? mipLevels - 1u : 0u;

			uint32_t selectedMip = std::min(renderResRegistry->GetIBLPrefilteredSpecularPreviewMip(), maxMip);
			if (selectedMip != renderResRegistry->GetIBLPrefilteredSpecularPreviewMip())
			{
				renderResRegistry->SetIBLPrefilteredSpecularPreviewMip(selectedMip);
			}

			int selectedMipInt = static_cast<int>(selectedMip);
			if (ImGui::SliderInt("Preview Mip", &selectedMipInt, 0, static_cast<int>(maxMip)))
			{
				selectedMip = static_cast<uint32_t>(std::clamp(selectedMipInt, 0, static_cast<int>(maxMip)));
				renderResRegistry->SetIBLPrefilteredSpecularPreviewMip(selectedMip);
			}

			const float roughness = maxMip > 0 ? static_cast<float>(selectedMip) / static_cast<float>(maxMip) : 0.0f;
			ImGui::Text("Approx Roughness: %.3f", roughness);

			using PreviewLayout = RenderResourceRegistry::IBLPreviewLayout;
			PreviewLayout previewLayout = renderResRegistry->GetIBLPrefilteredSpecularPreviewLayout();
			if (DrawPreviewLayoutCombo("Display Mode##PrefilteredSpecularPreviewLayout", previewLayout))
			{
				renderResRegistry->SetIBLPrefilteredSpecularPreviewLayout(previewLayout);
			}

			if (state.m_ShowMetadata)
			{
				const uint32_t prefilteredSpecularSrvIndex =
					renderResRegistry->GetShaderVisibleSrvIndex(PrefilteredSpecularIndex);
				const uint32_t previewSrvIndex =
					renderResRegistry->GetShaderVisibleSrvIndex(PrefilteredSpecularPreviewIndex);

				ImGui::Text("Cubemap Size: %llu x %u x %u",
					static_cast<unsigned long long>(prefilteredSpecularDesc->m_Extent.m_Width),
					prefilteredSpecularDesc->m_Extent.m_Height,
					prefilteredSpecularDesc->m_ArraySize);
				ImGui::Text("Cubemap MipLevels: %u", mipLevels);
				ImGui::Text("Cubemap Format: %s", devtools::EnumText(ToDXGIFormat(prefilteredSpecularDesc->m_Format)).data());
				ImGui::Text("Cubemap Shader Visible SRV Index: %u", prefilteredSpecularSrvIndex);

				ImGui::Text("Preview Canvas Size: %llu x %u",
					static_cast<unsigned long long>(prefilteredSpecularPreviewDesc->m_Extent.m_Width),
					prefilteredSpecularPreviewDesc->m_Extent.m_Height);
				ImGui::Text("Preview Format: %s", devtools::EnumText(ToDXGIFormat(prefilteredSpecularPreviewDesc->m_Format)).data());
				ImGui::Text("Preview Shader Visible SRV Index: %u", previewSrvIndex);
			}

			ImGui::SliderFloat(
				"Prefiltered Specular Preview Width",
				&state.m_PrefilteredSpecularPreviewWidth,
				192.0f,
				768.0f,
				"%.0f");

			const ImTextureID prefilteredSpecularPreviewTextureId =
				ToImGuiTextureID(
					renderer,
					renderResRegistry->GetSrvDescriptor(PrefilteredSpecularPreviewIndex));

			if (!prefilteredSpecularPreviewTextureId)
			{
				ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f), "Prefiltered specular preview SRV GPU handle is invalid.");
				return;
			}

			const float prefilteredSpecularPreviewWidth =
				std::clamp(state.m_PrefilteredSpecularPreviewWidth, 16.0f, 2048.0f);

			ImVec2 uv0(0.0f, 0.0f);
			ImVec2 uv1(1.0f, 1.0f);
			float aspect = 3.0f / 4.0f;
			const char* layoutHint = "Cross Layout: +Y / -X +Z +X -Z / -Y";

			if (previewLayout == RenderResourceRegistry::IBLPreviewLayout::Grid2x3)
			{
				uv1 = ImVec2(3.0f / 4.0f, 2.0f / 3.0f);
				aspect = 2.0f / 3.0f;
				layoutHint = "2x3 Layout: +X -X +Y / -Y +Z -Z";
			}

			const ImVec2 prefilteredSpecularImageSize(
				prefilteredSpecularPreviewWidth,
				prefilteredSpecularPreviewWidth * aspect);

			ImGui::TextUnformatted(layoutHint);
			ImGui::Image(prefilteredSpecularPreviewTextureId, prefilteredSpecularImageSize, uv0, uv1);
		}
	}
}
