#include "Core/Precompiled.h"
#include "Graphics/DevelopGui/DevelopGuiPBRPanel.h"
#include "Graphics/Renderer.h"

namespace gglab
{
	namespace
	{
		struct PBRPanelState
		{
			float m_BrdfLutPreviewSize = 256.0f;
			float m_EnvironmentPreviewWidth = 512.0f;
			bool m_ShowMetadata = true;
			bool m_FlipPreviewY = false;
		};

		static ImTextureID ToImGuiTextureID(D3D12_GPU_DESCRIPTOR_HANDLE handle) noexcept
		{
			return static_cast<ImTextureID>(handle.ptr);
		}

		static const char* FormatToString(DXGI_FORMAT format) noexcept
		{
			switch (format)
			{
			case DXGI_FORMAT_R16G16_FLOAT:
				return "DXGI_FORMAT_R16G16_FLOAT";
			case DXGI_FORMAT_R16G16B16A16_FLOAT:
				return "DXGI_FORMAT_R16G16B16A16_FLOAT";
			case DXGI_FORMAT_R8G8B8A8_UNORM:
				return "DXGI_FORMAT_R8G8B8A8_UNORM";
			case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB:
				return "DXGI_FORMAT_R8G8B8A8_UNORM_SRGB";
			default:
				return "Unknown / Other";
			}
		}

		static const char* PreviewLayoutToString(RenderResourceRegistry::IBLDebugPreviewLayout layout) noexcept
		{
			using Layout = RenderResourceRegistry::IBLDebugPreviewLayout;
			switch (layout)
			{
			case Layout::Grid2x3:
				return "2x3 Grid";
			case Layout::Cross:
				return "Cross";
			default:
				return "Unknown";
			}
		}
	}

	void DevelopGuiPBRPanel(DevelopGuiContext& context) noexcept
	{
		auto& state = context.PanelState<PBRPanelState>();

		ImGui::TextUnformatted("PBR");
		ImGui::Separator();

		auto* renderer = context.m_Renderer;
		if (!renderer)
		{
			ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f), "Renderer is null.");
			return;
		}

		auto* renderResRegistry = renderer->GetRenderResourceRegistry();
		if (!renderResRegistry)
		{
			ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f), "RenderResourceRegistry is null.");
			return;
		}

		using TextureIndex = RenderResourceRegistry::TextureIndex;
		constexpr TextureIndex EnvironmentIndex = TextureIndex::IBL_EnvironmentCubemap;
		constexpr TextureIndex EnvironmentPreviewIndex = TextureIndex::DebugPreview_IBL_EnvironmentCubemap;
		constexpr TextureIndex BrdfLutIndex = TextureIndex::IBL_BrdfLut;

		// Make sure the persistent BRDF LUT resource exists.
		// This only creates the texture and descriptor if missing.
		// Actual content is generated by RenderPassIBLBrdfLUT.
		renderResRegistry->EnsureIblResources();

		DX12Texture* brdfLutTexture = renderResRegistry->GetTexture(BrdfLutIndex);
		if (!brdfLutTexture)
		{
			ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f), "BRDF LUT texture is not allocated.");
			return;
		}

		const auto desc = brdfLutTexture->GetDesc();

		if (ImGui::CollapsingHeader("IBL BRDF LUT", ImGuiTreeNodeFlags_DefaultOpen))
		{
			if (ImGui::Button("Rebuild BRDF LUT"))
			{
				renderResRegistry->MarkDirty(BrdfLutIndex);
			}

			ImGui::SameLine();

			const bool isDirty = renderResRegistry->IsDirty(BrdfLutIndex);
			if (isDirty)
			{
				ImGui::TextColored(ImVec4(1.0f, 0.75f, 0.2f, 1.0f), "Dirty");
			}
			else
			{
				ImGui::TextColored(ImVec4(0.35f, 1.0f, 0.35f, 1.0f), "Ready");
			}

			ImGui::Checkbox("Show Metadata", &state.m_ShowMetadata);

			if (state.m_ShowMetadata)
			{
				const uint32_t bindlessIndex = renderResRegistry->GetBindlessSrvIndex(BrdfLutIndex);

				ImGui::Text("Size: %llu x %u",
					static_cast<unsigned long long>(desc.Width),
					static_cast<uint32_t>(desc.Height));

				ImGui::Text("MipLevels: %u", static_cast<uint32_t>(desc.MipLevels));
				ImGui::Text("Format: %s", FormatToString(desc.Format));
				ImGui::Text("Bindless SRV Index: %u", bindlessIndex);
			}

			ImGui::Separator();

			ImGui::SliderFloat(
				"Preview Size",
				&state.m_BrdfLutPreviewSize,
				64.0f,
				512.0f,
				"%.0f");

			ImGui::Checkbox("Flip Preview Y", &state.m_FlipPreviewY);

			D3D12_GPU_DESCRIPTOR_HANDLE gpuHandle = renderResRegistry->GetBindlessSrvGpuHandle(BrdfLutIndex);

			if (gpuHandle.ptr == 0)
			{
				ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f), "BRDF LUT SRV GPU handle is invalid.");
				return;
			}

			const ImTextureID textureId = ToImGuiTextureID(gpuHandle);
			const float previewSize = std::clamp(state.m_BrdfLutPreviewSize, 16.0f, 2048.0f);
			const ImVec2 imageSize(previewSize, previewSize);

			const ImVec2 uv0 = state.m_FlipPreviewY
				? ImVec2(0.0f, 1.0f)
				: ImVec2(0.0f, 0.0f);

			const ImVec2 uv1 = state.m_FlipPreviewY
				? ImVec2(1.0f, 0.0f)
				: ImVec2(1.0f, 1.0f);

			ImGui::TextUnformatted("Preview");
			ImGui::Image(textureId, imageSize, uv0, uv1);

			ImVec2 imageMin = ImGui::GetItemRectMin();
			ImVec2 imageMax = ImGui::GetItemRectMax();

			if (ImGui::IsItemHovered())
			{
				ImVec2 mouse = ImGui::GetMousePos();

				float u = (mouse.x - imageMin.x) / (imageMax.x - imageMin.x);
				float v = (mouse.y - imageMin.y) / (imageMax.y - imageMin.y);

				u = std::clamp(u, 0.0f, 1.0f);
				v = std::clamp(v, 0.0f, 1.0f);

				if (state.m_FlipPreviewY)
				{
					v = 1.0f - v;
				}

				ImGui::BeginTooltip();
				ImGui::Text("NoV: %.3f", u);
				ImGui::Text("Perceptual Roughness: %.3f", v);
				ImGui::EndTooltip();
			}

			ImGui::TextDisabled("Expected axis: X = NoV, Y = perceptual roughness.");
		}

		ImGui::Spacing();

		DX12Texture* environmentTexture = renderResRegistry->GetTexture(EnvironmentIndex);
		DX12Texture* environmentPreviewTexture = renderResRegistry->GetTexture(EnvironmentPreviewIndex);

		if (ImGui::CollapsingHeader("IBL Environment", ImGuiTreeNodeFlags_DefaultOpen))
		{
			if (ImGui::Button("Rebuild Environment"))
			{
				renderResRegistry->MarkDirty(EnvironmentIndex);
			}

			ImGui::SameLine();

			if (renderResRegistry->IsDirty(EnvironmentIndex))
			{
				ImGui::TextColored(ImVec4(1.0f, 0.75f, 0.2f, 1.0f), "Dirty");
			}
			else
			{
				ImGui::TextColored(ImVec4(0.35f, 1.0f, 0.35f, 1.0f), "Ready");
			}

			if (!environmentTexture || !environmentPreviewTexture)
			{
				ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f), "Environment preview texture is not allocated.");
				return;
			}

			const auto environmentDesc = environmentTexture->GetDesc();
			const auto environmentPreviewDesc = environmentPreviewTexture->GetDesc();

			using PreviewLayout = RenderResourceRegistry::IBLDebugPreviewLayout;
			PreviewLayout previewLayout = renderResRegistry->GetIBLDebugPreviewLayout();

			if (ImGui::BeginCombo("Display Mode", PreviewLayoutToString(previewLayout)))
			{
				const PreviewLayout layouts[] = {
					PreviewLayout::Grid2x3,
					PreviewLayout::Cross,
				};

				for (const auto layout : layouts)
				{
					const bool selected = (previewLayout == layout);
					if (ImGui::Selectable(PreviewLayoutToString(layout), selected))
					{
						renderResRegistry->SetIBLDebugPreviewLayout(layout);
						previewLayout = layout;
					}
					if (selected)
					{
						ImGui::SetItemDefaultFocus();
					}
				}

				ImGui::EndCombo();
			}

			if (state.m_ShowMetadata)
			{
				const uint32_t environmentBindlessIndex = renderResRegistry->GetBindlessSrvIndex(EnvironmentIndex);
				const uint32_t previewBindlessIndex = renderResRegistry->GetBindlessSrvIndex(EnvironmentPreviewIndex);

				ImGui::Text("Environment Size: %llu x %u x %u",
					static_cast<unsigned long long>(environmentDesc.Width),
					static_cast<uint32_t>(environmentDesc.Height),
					static_cast<uint32_t>(environmentDesc.DepthOrArraySize));
				ImGui::Text("Environment Format: %s", FormatToString(environmentDesc.Format));
				ImGui::Text("Environment Bindless SRV Index: %u", environmentBindlessIndex);

				ImGui::Text("Preview Canvas Size: %llu x %u",
					static_cast<unsigned long long>(environmentPreviewDesc.Width),
					static_cast<uint32_t>(environmentPreviewDesc.Height));
				ImGui::Text("Preview Format: %s", FormatToString(environmentPreviewDesc.Format));
				ImGui::Text("Preview Bindless SRV Index: %u", previewBindlessIndex);
			}

			ImGui::SliderFloat(
				"Environment Preview Width",
				&state.m_EnvironmentPreviewWidth,
				192.0f,
				768.0f,
				"%.0f");

			D3D12_GPU_DESCRIPTOR_HANDLE environmentPreviewGpuHandle =
				renderResRegistry->GetBindlessSrvGpuHandle(EnvironmentPreviewIndex);

			if (environmentPreviewGpuHandle.ptr == 0)
			{
				ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.35f, 1.0f), "Environment preview SRV GPU handle is invalid.");
				return;
			}

			const ImTextureID environmentPreviewTextureId = ToImGuiTextureID(environmentPreviewGpuHandle);
			const float environmentPreviewWidth = std::clamp(state.m_EnvironmentPreviewWidth, 16.0f, 2048.0f);

			ImVec2 uv0(0.0f, 0.0f);
			ImVec2 uv1(1.0f, 1.0f);
			float aspect = 3.0f / 4.0f;
			const char* layoutHint = "Cross Layout: +Y / -X +Z +X -Z / -Y";

			if (previewLayout == PreviewLayout::Grid2x3)
			{
				uv1 = ImVec2(3.0f / 4.0f, 2.0f / 3.0f);
				aspect = 2.0f / 3.0f;
				layoutHint = "2x3 Layout: +X -X +Y / -Y +Z -Z";
			}

			const ImVec2 environmentImageSize(environmentPreviewWidth, environmentPreviewWidth * aspect);

			ImGui::TextUnformatted(layoutHint);
			ImGui::Image(environmentPreviewTextureId, environmentImageSize, uv0, uv1);
	}
}
}
