<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <ShaderSrcDir>$(SolutionDir)Shaders</ShaderSrcDir>
    <ShaderOutDir>$(OutDir)Shaders</ShaderOutDir>
    <_IsAppProject Condition="'$(ConfigurationType)'=='Application'">true</_IsAppProject>
  </PropertyGroup>
</Project>
